# Generated by Django 4.2.2 on 2023-08-02 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('userid', models.CharField(default='none', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
                ('designation', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('yearsOfExperience', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(default='Approved', max_length=8, primary_key=True, serialize=False)),
                ('managerId', models.CharField(max_length=6, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('leave_type', models.CharField(max_length=15)),
                ('from_date', models.CharField(max_length=50)),
                ('till_date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('approver', models.CharField(default='HR', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(default='Pending', max_length=8)),
                ('employeeId', models.CharField(max_length=6, unique=True)),
                ('approverId', models.CharField(max_length=6, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('leave_type', models.CharField(max_length=15, null=True)),
                ('from_date', models.DateField(null=True)),
                ('till_date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('approver', models.CharField(default='manager', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Manager',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('managerId', models.CharField(max_length=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveApp.employees')),
            ],
        ),
    ]
